//
//  SessionTitleSummary.swift
//  OpenCodeClient
//

import Foundation

/// Pure, display-only helpers for turning a session + its loaded messages into a
/// one-line intent summary for the row. Never mutates server state.
///
/// If a session's title looks auto-generated (empty, or a "New session - <ISO8601>"
/// style placeholder), the summary is derived from the first user message text.
/// Otherwise the existing title is returned unchanged.
enum SessionTitleSummary {
    /// Max characters of derived first-message text shown in the summary.
    static let maxLength = 50

    /// Returns a one-line intent summary for a session.
    ///
    /// - Parameters:
    ///   - session: The session whose title to summarize.
    ///   - messages: The session's loaded messages (newest-last). May be empty.
    /// - Returns: The existing title if it is meaningful; otherwise a truncated
    ///   single-line derivation of the first user message, or the original title
    ///   as a last resort.
    static func summary(for session: Session, messages: [MessageWithParts]) -> String {
        let title = session.title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !isAutoGenerated(title) {
            return title
        }
        if let derived = firstUserMessageSummary(messages: messages) {
            return derived
        }
        return title
    }

    /// True if `title` is empty or matches an auto-generated placeholder pattern
    /// (e.g. "New session - 2026-06-07T12:34:56Z").
    static func isAutoGenerated(_ title: String) -> Bool {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return true }
        // "New session" optionally followed by a separator + ISO8601-ish timestamp.
        let pattern = #"(?i)^new session\b.*\d{4}-\d{2}-\d{2}t\d{2}:\d{2}"#
        if trimmed.range(of: pattern, options: .regularExpression) != nil {
            return true
        }
        // Bare "New session" with no further intent.
        if trimmed.range(of: #"(?i)^new session\b\s*$"#, options: .regularExpression) != nil {
            return true
        }
        return false
    }

    /// Extracts the first user message's text, collapsed to a single line and
    /// truncated to `maxLength`. Returns nil if there is no usable user text.
    /// Mirrors the first-user-message extraction in `AppState+Messages.swift`.
    static func firstUserMessageSummary(messages: [MessageWithParts]) -> String? {
        guard let firstUser = messages.first(where: { $0.info.isUser }) else { return nil }
        let raw = firstUser.parts.first(where: { $0.isText })?.text ?? ""
        let singleLine = raw
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        guard !singleLine.isEmpty else { return nil }
        if singleLine.count <= maxLength {
            return singleLine
        }
        let endIndex = singleLine.index(singleLine.startIndex, offsetBy: maxLength)
        return String(singleLine[..<endIndex]).trimmingCharacters(in: .whitespaces) + "…"
    }
}
